services:
  - type: web
    name: womenday-app
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn appwomenday:app #fixed
    envVars:
      CLOUDINARY_CLOUD_NAME:
        fromSecret: CLOUDINARY_CLOUD_NAME
      CLOUDINARY_API_KEY:
        fromSecret: CLOUDINARY_API_KEY
      CLOUDINARY_API_SECRET:

        fromSecret: CLOUDINARY_API_SECRET

